<?php

namespace App\Modules\StorefrontBuilder\Services;

/**
 * Serves extracted Uomo HTML fragments (Phase 3B) from storage/app/uomo-fragments/.
 * Files are generated by `php artisan storefront:extract-uomo-navbar-fragments`.
 */
class UomoFragmentService
{
    /**
     * Restrict fragment rendering to structural navbar markup only.
     *
     * @var array<string, true>
     */
    private const ALLOWED_TAGS = [
        'a' => true,
        'button' => true,
        'div' => true,
        'form' => true,
        'header' => true,
        'i' => true,
        'img' => true,
        'input' => true,
        'label' => true,
        'li' => true,
        'nav' => true,
        'ol' => true,
        'option' => true,
        'p' => true,
        'section' => true,
        'select' => true,
        'small' => true,
        'span' => true,
        'strong' => true,
        'ul' => true,
    ];

    /**
     * Attributes accepted globally on allowed tags.
     *
     * @var array<string, true>
     */
    private const ALLOWED_GLOBAL_ATTRIBUTES = [
        'alt' => true,
        'aria-current' => true,
        'aria-expanded' => true,
        'aria-hidden' => true,
        'aria-label' => true,
        'aria-labelledby' => true,
        'aria-selected' => true,
        'class' => true,
        'data-bs-dismiss' => true,
        'data-bs-target' => true,
        'data-bs-toggle' => true,
        'data-target' => true,
        'data-toggle' => true,
        'height' => true,
        'id' => true,
        'name' => true,
        'placeholder' => true,
        'rel' => true,
        'role' => true,
        'src' => true,
        'tabindex' => true,
        'title' => true,
        'type' => true,
        'value' => true,
        'width' => true,
    ];

    /**
     * Navbar HTML files available for the active template (studio presets / portal).
     *
     * @return list<array{key: string, fragment_file: string, has_html: bool}>
     */
    public function listNavbarPresets(): array
    {
        $dir = storage_path('app/uomo-fragments');
        if (!is_dir($dir)) {
            return [];
        }

        $out = [];
        foreach (glob($dir . '/navbar-uomo-home-*.html') ?: [] as $path) {
            $base = basename($path, '.html');
            if (!preg_match('/^navbar-(uomo-home-\d+)$/', $base, $m)) {
                continue;
            }
            $out[] = [
                'key' => $m[1],
                'fragment_file' => $base . '.html',
                'has_html' => is_file($path) && (int) @filesize($path) > 0,
            ];
        }

        usort($out, fn ($a, $b) => strcmp($a['key'], $b['key']));

        return $out;
    }

    public function navbarHtml(string $uomoHomeKey): ?string
    {
        if (!preg_match('/^uomo-home-\d+$/', $uomoHomeKey)) {
            return null;
        }

        $path = storage_path('app/uomo-fragments/navbar-' . $uomoHomeKey . '.html');
        if (!is_file($path)) {
            return null;
        }

        $html = file_get_contents($path);
        if ($html === false || trim($html) === '') {
            return null;
        }

        return $this->sanitizeHtml($html);
    }

    private function sanitizeHtml(string $html): ?string
    {
        $dom = new \DOMDocument();
        libxml_use_internal_errors(true);
        $loaded = $dom->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
        libxml_clear_errors();
        if (!$loaded) {
            return null;
        }

        $xpath = new \DOMXPath($dom);

        foreach ($xpath->query('//*') ?: [] as $node) {
            if (!$node instanceof \DOMElement) {
                continue;
            }

            $tagName = strtolower($node->tagName);
            if (!isset(self::ALLOWED_TAGS[$tagName])) {
                $node->parentNode?->removeChild($node);
            }
        }

        foreach ($xpath->query('//*') ?: [] as $el) {
            if (!$el instanceof \DOMElement) {
                continue;
            }
            $removeAttrs = [];
            foreach ($el->attributes ?? [] as $attr) {
                $name = strtolower((string) $attr->nodeName);
                $value = trim((string) $attr->nodeValue);
                $tagName = strtolower($el->tagName);

                if (!isset(self::ALLOWED_GLOBAL_ATTRIBUTES[$name])) {
                    if (!(str_starts_with($name, 'data-') || str_starts_with($name, 'aria-'))) {
                        $removeAttrs[] = $attr->nodeName;
                        continue;
                    }
                }

                if (str_starts_with($name, 'on')) {
                    $removeAttrs[] = $attr->nodeName;
                    continue;
                }

                if (
                    in_array($name, ['href', 'src', 'action', 'formaction'], true)
                    && !$this->isSafeUrl($value, $name, $tagName)
                ) {
                    $removeAttrs[] = $attr->nodeName;
                    continue;
                }
            }
            foreach ($removeAttrs as $attrName) {
                $el->removeAttribute($attrName);
            }
        }

        $clean = trim((string) $dom->saveHTML());

        return $clean !== '' ? $clean : null;
    }

    private function isSafeUrl(string $url, string $attribute, string $tagName): bool
    {
        $normalized = preg_replace('/[\x00-\x20]+/u', '', $url) ?? '';
        if ($normalized === '') {
            return true;
        }

        if (str_starts_with($normalized, '#') || str_starts_with($normalized, '/')) {
            return true;
        }

        if (preg_match('/^(?:https?:|mailto:|tel:)/i', $normalized)) {
            return true;
        }

        if ($tagName === 'img' && $attribute === 'src' && preg_match('/^data:image\//i', $normalized)) {
            return true;
        }

        return false;
    }
}
