<?php

namespace App\Modules\StorefrontBuilder\Services;

/**
 * Serves extracted Uomo HTML fragments (Phase 3B) from storage/app/uomo-fragments/.
 * Files are generated by `php artisan storefront:extract-uomo-navbar-fragments`.
 */
class UomoFragmentService
{
    /**
     * Navbar HTML files available for the active template (studio presets / portal).
     *
     * @return list<array{key: string, fragment_file: string, has_html: bool}>
     */
    public function listNavbarPresets(): array
    {
        $dir = storage_path('app/uomo-fragments');
        if (!is_dir($dir)) {
            return [];
        }

        $out = [];
        foreach (glob($dir . '/navbar-uomo-home-*.html') ?: [] as $path) {
            $base = basename($path, '.html');
            if (!preg_match('/^navbar-(uomo-home-\d+)$/', $base, $m)) {
                continue;
            }
            $out[] = [
                'key' => $m[1],
                'fragment_file' => $base . '.html',
                'has_html' => is_file($path) && (int) @filesize($path) > 0,
            ];
        }

        usort($out, fn ($a, $b) => strcmp($a['key'], $b['key']));

        return $out;
    }

    public function navbarHtml(string $uomoHomeKey): ?string
    {
        if (!preg_match('/^uomo-home-\d+$/', $uomoHomeKey)) {
            return null;
        }

        $path = storage_path('app/uomo-fragments/navbar-' . $uomoHomeKey . '.html');
        if (!is_file($path)) {
            return null;
        }

        $html = file_get_contents($path);
        if ($html === false || trim($html) === '') {
            return null;
        }

        return $this->sanitizeHtml($html);
    }

    private function sanitizeHtml(string $html): ?string
    {
        $dom = new \DOMDocument();
        libxml_use_internal_errors(true);
        $loaded = $dom->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
        libxml_clear_errors();
        if (!$loaded) {
            return null;
        }

        $xpath = new \DOMXPath($dom);

        foreach ($xpath->query('//script | //iframe | //object | //embed | //link[translate(@rel, "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz")="import"]') ?: [] as $node) {
            $node->parentNode?->removeChild($node);
        }

        foreach ($xpath->query('//*') ?: [] as $el) {
            if (!$el instanceof \DOMElement) {
                continue;
            }
            $removeAttrs = [];
            foreach ($el->attributes ?? [] as $attr) {
                $name = strtolower((string) $attr->nodeName);
                $value = trim((string) $attr->nodeValue);
                if (str_starts_with($name, 'on')) {
                    $removeAttrs[] = $attr->nodeName;
                    continue;
                }
                if (in_array($name, ['src', 'href', 'xlink:href', 'formaction'], true) && preg_match('/^\s*javascript:/i', $value)) {
                    $removeAttrs[] = $attr->nodeName;
                    continue;
                }
                if ($name === 'style' && preg_match('/expression\s*\(|url\s*\(\s*["\']?\s*javascript:/i', $value)) {
                    $removeAttrs[] = $attr->nodeName;
                }
            }
            foreach ($removeAttrs as $attrName) {
                $el->removeAttribute($attrName);
            }
        }

        $clean = trim((string) $dom->saveHTML());

        return $clean !== '' ? $clean : null;
    }
}
